#!/bin/bash

# Based on https://gist.github.com/1211638/5d0ee7da6f2db49ecd2a9268422a5d268d33b362
# Thanks to mhl!

set -e
shopt -s nullglob

cd "$(git rev-parse --show-cdup)"

# Find all the objects that are in packs:

for p in .git/objects/pack/pack-*.idx
do
    git show-index < $p | cut -f 2 -d ' '
done

# And now find all loose objects:

find .git/objects/ | egrep '[0-9a-f]{38}$' | \
  sed -r 's,^.*([0-9a-f][0-9a-f])/([0-9a-f]{38}),\1\2,'
